server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: larry
    password: CQH?wot^x@q,

eureka:
  client:
    #是否向注册中心注册自己
    register-with-eureka: true
    #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    fetchRegistry: true
    service-url:
       #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
       #单机版
       #defaultZone: http://localhost:7001/eureka
       #集群版
       defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities